# Generated by Django 3.0.6 on 2020-06-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=60)),
                ('assignment', models.FileField(upload_to='assignments')),
                ('unit_id', models.CharField(max_length=15)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
