# Generated by Django 3.0.6 on 2020-06-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
